# Generated by Django 6.0.3 on 2026-03-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='completada',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='titulo',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
