# Generated by Django 6.0.3 on 2026-04-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_seccion_tarea_prioridad_tarea_seccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='prioridad_orden',
            field=models.IntegerField(default=2, editable=False),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='prioridad',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10),
        ),
    ]
