# Generated by Django 6.0.3 on 2026-04-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_tarea_prioridad_orden_alter_tarea_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
